[package]
name = "meilitool"
description = "A CLI to edit a Meilisearch database from the command line"
version.workspace = true
authors.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
dump = { path = "../dump" }
file-store = { path = "../file-store" }
indexmap = { workspace = true, features = ["serde"] }
meilisearch-auth = { path = "../meilisearch-auth" }
meilisearch-types = { path = "../meilisearch-types" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
tempfile.workspace = true
time = { workspace = true, features = ["formatting", "parsing", "alloc"] }
uuid = { workspace = true, features = ["v4"], default-features = false }
