[package]
name = "meili-snap"
publish = false

version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
insta = { workspace = true, features = ["json", "redactions"] }
md5.workspace = true
once_cell.workspace = true
regex-lite.workspace = true
uuid = { workspace = true, features = ["v4"] }
