[package]
name = "index-scheduler"
publish = false

version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bincode.workspace = true
byte-unit.workspace = true
bumpalo.workspace = true
bumparaw-collections.workspace = true
convert_case.workspace = true
csv.workspace = true
derive_builder.workspace = true
dump.path = "../dump"
enum-iterator.workspace = true
file-store.path = "../file-store"
flate2.workspace = true
indexmap.workspace = true
meilisearch-auth.path = "../meilisearch-auth"
meilisearch-types.path = "../meilisearch-types"
memmap2.workspace = true
page_size.workspace = true
rayon.workspace = true
roaring = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
synchronoise.workspace = true
tempfile.workspace = true
thiserror.workspace = true
time = { workspace = true, features = [
    "serde-well-known",
    "formatting",
    "parsing",
    "macros",
] }
tracing.workspace = true
ureq.workspace = true
uuid = { workspace = true, features = ["serde", "v4"] }

[dev-dependencies]
big_s.workspace = true
crossbeam-channel.workspace = true
insta = { workspace = true, features = ["json", "redactions"] }
maplit.workspace = true
meili-snap.path = "../meili-snap"
