[package]
name = "benchmarks"
publish = false

version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bumpalo.workspace = true
csv.workspace = true
memmap2.workspace = true
milli.path = "../milli"
mimalloc.workspace = true
serde_json = { workspace = true, features = ["preserve_order"] }
tempfile.workspace = true

[dev-dependencies]
criterion = { workspace = true, features = ["html_reports"] }
rand.workspace = true
rand_chacha.workspace = true
roaring.workspace = true

[build-dependencies]
anyhow.workspace = true
bytes.workspace = true
convert_case.workspace = true
flate2.workspace = true
reqwest = { workspace = true, features = ["blocking", "rustls-tls"], default-features = false }

[features]
default = ["milli/all-tokenizations"]

[[bench]]
name = "search_songs"
harness = false

[[bench]]
name = "search_wiki"
harness = false

[[bench]]
name = "search_geo"
harness = false

[[bench]]
name = "indexing"
harness = false
