[package]
name = "meilisearch-auth"
publish = false

version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
enum-iterator.workspace = true
hmac.workspace = true
maplit.workspace = true
meilisearch-types = { path = "../meilisearch-types" }
rand.workspace = true
roaring = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
sha2.workspace = true
thiserror.workspace = true
time = { workspace = true, features = ["serde-well-known", "formatting", "parsing", "macros"] }
uuid = { workspace = true, features = ["serde", "v4"] }
