[package]
name = "fuzzers"
publish = false

version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arbitrary = { workspace = true, features = ["derive"] }
bumpalo.workspace = true
clap = { workspace = true, features = ["derive"] }
either.workspace = true
fastrand.workspace = true
milli = { path = "../milli" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
tempfile.workspace = true
