[package]
name = "dump"
publish = false

version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
flate2.workspace = true
http.workspace = true
meilisearch-types = { path = "../meilisearch-types" }
once_cell.workspace = true
regex.workspace = true
roaring = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
tar.workspace = true
tempfile.workspace = true
thiserror.workspace = true
time = { workspace = true, features = ["serde-well-known", "formatting", "parsing", "macros"] }
tracing.workspace = true
uuid = { workspace = true, features = ["serde", "v4"] }

[dev-dependencies]
big_s.workspace = true
maplit.workspace = true
meili-snap = { path = "../meili-snap" }
meilisearch-types = { path = "../meilisearch-types" }
