[package]
name = "flatten-serde-json"
description = "Flatten serde-json objects like elastic search"
readme = "README.md"
publish = false

version.workspace = true
authors.workspace = true
# description.workspace = true
homepage.workspace = true
# readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true

[dev-dependencies]
criterion = { workspace = true, features = ["html_reports"] }

[[bench]]
name = "benchmarks"
harness = false
