[package]
name = "tracing-trace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-spantrace.workspace = true
fxprof-processed-profile.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing.workspace = true
tracing-error.workspace = true
tracing-subscriber.workspace = true
byte-unit = { workspace = true, default-features = false, features = [
    "std",
    "byte",
    "serde",
] }
tokio = { workspace = true, features = ["sync"] }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
libproc.workspace = true
